model:
  ATTN:
    n_heads: 8
    attention_probs_dropout_prob: 0.1
    hidden_dropout_prob: 0.1  
    cell_input_hidden_dropout_prob: 0.1
    drug_input_hidden_dropout_prob: 0.1
    topk_cell: 128
    topk_drug: 32
    sparse_flag: False
    hidden_size: 256
    trt_structure: CA+SA+SA+CA
    ctl_structure: SA+SA+SA+SA
    ppi_gene_vector_path: processed_data/PPI_gene_vector_128d.npy
  HG:
    node_input_dim: 512
    conv_layers: 2
    hg_path: HG_data/
    drug_hg_pretrained_embed_path: HG_data/saved_embedding/HG_drug_embeddings.npy


dataset:
  n_bins: 128
  gene_num: 978
  atom_num: 24
  max_atom_size: 122
  max_value: 15.002
  min_value: 0.0

  l1000:
    num_pert_dose: 10
    num_pert_time: 3
    num_cell_id: 240
    num_tissue_id: 21
  panacea:
    num_pert_dose: 10
    num_pert_time: 3  
    num_cell_id: 240
    num_tissue_id: 21
  cdsdb:
    num_pert_dose: 11
    num_pert_time: 8
    num_cell_id: 14
    num_tissue_id: 14

  l1000_sdst_data_root: processed_data/l1000_sdst_78453.h5ad
  l1000_mdmt_data_root: processed_data/l1000_mdmt_68830_subset.h5ad
  l1000_mdmt_pretrain_data_root: processed_data/l1000_mdmt_268022_pretrain.h5ad
  l1000_mdmt_full_data_root: processed_data/l1000_mdmt_full_336852.h5ad

  drug_unimol_path: processed_data/all_drugs_unimol_arr.npy
  drug_KPGT_path: processed_data/all_drugs_idx2KPGT.npy
  drug_smi_path: processed_data/all_drugs_idx2smi_8981.npy
  drug_morgan_path: processed_data/all_drugs_idx2morgan.npy


train:
  train_lr: 0.004
  weight_decay: 0.00001
  batch_size: 128 
  num_epochs: 2500
  init_epoch: 70
  loss_weight: [0.2, 0.003, 0.2, 1]
  patience: 50
  bandwidth: 0.3

finetune:
  finetune_params: all
  exclude_keys: []
  init_epoch: 0
  finetune_lr: 0.001  # 0.001 for code_dose_time scenario, 0.002 for indenpendent datasets
  weight_decay: 0.00001